### ISSUE TITLE
Broken on when updating to 1.4.3 on Ubuntu

### ISSUE THREAD

**Issue by lackdaz** [panz3r/hyper-spotify#9]
All I see is a blank screen now.

Errors logs in Dev console:
```Uncaught Error: Cannot find module 'abstract-socket'
    at Module._resolveFilename (module.js:470)
    at Function.Module._resolveFilename (/opt/Hyper/resources/electron.asar/common/reset-search-paths.js:35)
    at Function.Module._load (module.js:418)
    at Function.c._load (bundle.js:1)
    at Module.require (module.js:498)
    at require (internal/module.js:20)
    at createStream (/home/lackdaz/.hyper_plugins/node_modules/dbus-native/index.js:49)
    at createConnection (/home/lackdaz/.hyper_plugins/node_modules/dbus-native/index.js:84)
    at Function.module.exports.createClient (/home/lackdaz/.hyper_plugins/node_modules/dbus-native/index.js:144)
    at Function.module.exports.sessionBus (/home/lackdaz/.hyper_plugins/node_modules/dbus-native/index.js:155)```

```Uncaught Error: Minified React error #136; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=136&args[]=_class for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at e.exports (bundle.js:1)
    at c.updateComponent (bundle.js:4)
    at c.receiveComponent (bundle.js:4)
    at Object.receiveComponent (bundle.js:1)
    at Object.updateChildren (bundle.js:4)
    at ReactDOMComponent._reconcilerUpdateChildren (bundle.js:4)
    at ReactDOMComponent._updateChildren (bundle.js:4)
    at ReactDOMComponent.updateChildren (bundle.js:4)
    at ReactDOMComponent._updateDOMChildren (bundle.js:4)
    at ReactDOMComponent.updateComponent (bundle.js:4)```

**Comment by panz3r** [comment]
Hi @lackdaz ,
I'm sorry to hear you are having this issue with `hyper-spotify`.

I tried to reproduce this on an Ubuntu 17.04 but without success, everything works fine for me.

The log you posted seems to be missing the initial part (just before `at Module._resolveFilename (module.js:470`) that should say what went wrong, can you please reproduce the issue and paste here a complete log?

You can also try to remove and then re-install `hyper-spotify`.

**Comment by lackdaz** [comment]
`Uncaught Error: Cannot find module 'abstract-socket'`

**Comment by panz3r** [comment]
Hi @lackdaz ,
Thanks for your feedback.

You can try to re-install (or force install) the `abstract-socket` module.
To do so, run the following
```bash
$ cd ~/.hyper_plugins && npm install abstract-socket
```

Let me know if it works, in the case it doesn't can you please run `node -v` and `npm version` and paste the results here

**Comment by lackdaz** [comment]
@panz3r  I've tried reinstalling abstract-socket to no avail

my node version is `v8.7.0` amd npm version is `5.5.1`

**Comment by panz3r** [comment]
Hi @lackdaz  ,

Can you try to run the following commands and post here the resulting files
```bash
$ cd ~/.hyper_plugins
$ npm ls > ~/npm_deps_tree.txt
$ ls > ~/npm_deps_list.txt
```

**Comment by lackdaz** [comment]
`npm_deps_tree.txt`
```
hyper-plugins@0.0.1 /home/lackdaz/.hyper_plugins
├── UNMET DEPENDENCY abstract-socket@2.0.0
├── UNMET DEPENDENCY gitrocket@latest
├── UNMET DEPENDENCY hypercwd@latest
├── UNMET DEPENDENCY hyperemoji@latest
├── UNMET DEPENDENCY hyperline@latest
├── UNMET DEPENDENCY hyperpower@latest
└── UNMET DEPENDENCY hyperterm-material-spacegray@latest
```
`npm_deps_list.txt`
```
cache
local
node_modules
package.json
package-lock.json
```

**Comment by panz3r** [comment]
Hi @lackdaz ,

I don't see `hyper-spotify` inside your npm dependency tree, try to remove `abstract-socket` and re-install `hyper-spotify` (following the installation instruction from the [README](https://github.com/panz3r/hyper-spotify/blob/master/README.md))

Run again the following commands and post the results here
```
$ cd ~/.hyper_plugins
$ npm ls > ~/npm_deps_tree.txt
$ ls ./node_modules > ~/npm_deps_list.txt
```
(please note that the last one is different from before, last time I missed a folder)

**Comment by panz3r** [comment]
Closed due to inactivity
